#!/bin/bash

ME=${0##*/}

ZDIR=/usr/share/zoneinfo
SDIR=/etc/apt/sources.list.d

MIRROR_PREFIXES="co de dk ec fr gr it la nl nz pl ru se tw ut"
HOST_PREFIXES="$MIRROR_PREFIXES old_us"
HOST_TYPES="AX MX"
US_HOST_LIST="la ut"

co_AX_HOST=http://mirror.upb.edu.co/mx-workspace/antix
#co_MP_HOST=http://mirror.upb.edu.co/mx-workspace/mepiscr
co_MX_HOST=http://mirror.upb.edu.co/mx-workspace/mx
co_LOCATION="Colombia"

de_AX_HOST=http://ftp.halifax.rwth-aachen.de/mxlinux/packages/antix
#de_MP_HOST=http://ftp.halifax.rwth-aachen.de/mxlinux/packages/mepiscr
de_MX_HOST=http://ftp.halifax.rwth-aachen.de/mxlinux/packages/mx
de_LOCATION="Germany"

dk_AX_HOST=http://mirrors.dotsrc.org/mx-packages/antix
#dk_MP_HOST=http://mirrors.dotsrc.org/mx-packages/mepiscr
dk_MX_HOST=http://mirrors.dotsrc.org/mx-packages/mx
dk_LOCATION="Denmark"

ec_AX_HOST=http://mirror.cedia.org.ec/mx-workspace/antix
#ec_MP_HOST=http://mirror.cedia.org.ec/mx-workspace/mepiscr
ec_MX_HOST=http://mirror.cedia.org.ec/mx-workspace/mx
ec_LOCATION="Ecuador"

fr_AX_HOST=http://fr.mirror.mxlinux.de/packages/antix
#fr_MP_HOST=http://fr.mirror.mxlinux.de/packages/mepiscr
fr_MX_HOST=http://fr.mirror.mxlinux.de/packages/mx
fr_LOCATION="France"

gr_AX_HOST=http://ftp.cc.uoc.gr/mirrors/linux/mx/antix
#gr_MP_HOST=http://ftp.cc.uoc.gr/mirrors/linux/mx/mepiscr
gr_MX_HOST=http://ftp.cc.uoc.gr/mirrors/linux/mx/mx
gr_LOCATION="Greece"

it_AX_HOST=http://it.mxrepo.com/antix
#it_MP_HOST=http://it.mxrepo.com/mepiscr
it_MX_HOST=http://it.mxrepo.com/mx
it_LOCATION="Italy"

la_AX_HOST=http://iso.mxrepo.com/antix
#la_MP_HOST=http://iso.mxrepo.com/mepiscr
la_MX_HOST=http://iso.mxrepo.com/mx
la_LOCATION="Los Angeles, USA"

nl_AX_HOST=http://nl.mxrepo.com/antix
#nl_MP_HOST=http://nl.mxrepo.com/mepiscr
nl_MX_HOST=http://nl.mxrepo.com/mx
nl_LOCATION="The Netherlands"

nz_AX_HOST=http://mx.debian.nz/antix
#nz_MP_HOST=http://mx.debian.nz/mepiscr
nz_MX_HOST=http://mx.debian.nz/mx
nz_LOCATION="New Zealand"

pl_AX_HOST=http://ftp.icm.edu.pl/pub/Linux/dist/antix-workspace/antix
#pl_MP_HOST=http://ftp.icm.edu.pl/pub/Linux/dist/antix-workspace/mepiscr
pl_MX_HOST=http://ftp.icm.edu.pl/pub/Linux/dist/antix-workspace/mx
pl_LOCATION="Poland"

ru_AX_HOST=http://mirror.truenetwork.ru/mxlinux/antix
#ru_MP_HOST=http://mirror.truenetwork.ru/mxlinux/mepiscr
ru_MX_HOST=http://mirror.truenetwork.ru/mxlinux/mx
ru_LOCATION="Russia"

se_AX_HOST=http://ftp.acc.umu.se/mirror/mxlinux.org/packages/antix
#se_MP_HOST=http://ftp.acc.umu.se/mirror/mxlinux.org/packages/mepiscr
se_MX_HOST=http://ftp.acc.umu.se/mirror/mxlinux.org/packages/mx
se_LOCATION="Sweden"

tw_AX_HOST=http://ftp.yzu.edu.tw/Linux/mx-workspace/antix
#tw_MP_HOST=http://ftp.yzu.edu.tw/Linux/mx-workspace/mepiscr
tw_MX_HOST=http://ftp.yzu.edu.tw/Linux/mx-workspace/mx
tw_LOCATION="Taiwan"

ut_AX_HOST=http://repo.antixlinux.com
#ut_MP_HOST=http://mxrepo.com/mepiscr
ut_MX_HOST=http://mxrepo.com/mx
ut_LOCATION="Utah, USA"

old_us_AX_HOST=http://repo.antixlinux.com
#old_us_MP_HOST=http://main.mepis-deb.org/mepiscr
old_us_MX_HOST=http://main.mepis-deb.org/mx

usage() {
    local ret=${1:-0}
    cat<<Usage
Usage: $me [options] <timezone|country-code|"default">

Update the mirrors in the *.list files under $SDIR/
with the closest mirrors based on timezone city or two-letter
country code.  If "default" is given then use the timezone
in the /etc/timezone file.

Options:
    -c --codes          Only display codes for the servers that would
                        be used for the given timezone
    -d --dir=<dir>      Use <dir> instead of $SDIR
    -h --help           Show this help
    -H --hosts          Only show the hosts that would be used for the
                        given timezone
    -i --ignore=<list>  Comma delimited list of MX/antiX mirrors to ignore
                        Codes: $MIRROR_PREFIXES
    -L --list           List all the mirror locations
    -p --pretend        Don't do anything just show what would be done
    -r --random         When a US city is closest, use any US mirror at random
    -q --quiet          Print less
    -v --verbose        Print more
Usage

    exit $ret
}

main() {
    local param val short_stack="cdhHiLpqrv"
    while [ $# -gt 0 -a -n "$1" -a -z "${1##-*}" ]; do
        param=${1#-}
        shift

        case $param in
            [$short_stack][$short_stack]*)
                if [ -z "${param//[$short_stack]/}" ]; then
                    set -- $(echo $param | sed -r 's/([a-zA-Z])/ -\1 /g') "$@"
                    continue
                fi;;
        esac

        case $param in
          -dir|-ignore|[di]) [ $# -lt 1 ] && fatal "Expected a parameter after: -$param"
                    val=$1
                    [ -n "$val" -a -z "${val##-*}" ] \
                        && fatal "Suspicious parameter after -$param: $val"

                    shift           ;;
              *=*)  val=${param#*=} ;;
                *)  val="???"       ;;
        esac

        case $param in
          -ignore|i) IGNORE=$val                       ;;
      -ignore=*|i=*) IGNORE=$val                       ;;
           -codes|c) CODES_ONLY=true                   ;;
         -dir=*|d=*) SDIR=$val                         ;;
             -dir|d) SDIR=$val                         ;;
            -help|h) usage                             ;;
           -hosts|H) HOSTS_ONLY=true                   ;;
            -list|L) LIST_MIRRORS=true                 ;;
         -pretend|p) PRETEND=true                      ;;
           -quiet|q) QUIET=true                        ;;
          -random|r) RANDOMIZE=true                    ;;
         -verbose|v) VERBOSE=true                      ;;
                  *) fatal "Unknown argument: -$param" ;;
        esac
    done

    if [ "$LIST_MIRRORS" ]; then
        if [ "$VERBOSE" ]; then
            list_mirrors
        else
            list_mirror_codes
        fi
        exit 0
    fi

    [ $# -lt 1 ] && usage
    [ $# -gt 1 ] && fatal "Only expected one command line argument"

    local tz=$1

    case $tz in
        */UTC) not_setting $tz ;;
    esac

    local tz_file=/etc/timezone
    if [ "$tz" = "default" ]; then
        test -r $tz_file || fatal "Could not find file $tz_file"
        read tz 2>/dev/null <$tz_file
        vsay "Current timezone: $tz"
    fi

    [ ${#tz} -lt 1 ] && fatal "Timezone or country code too short: $tz"

    case $tz in
        [a-zA-Z][a-zA-Z]) country_code_to_timezone $tz
                          tz=$NEW_TZ ;;
    esac

    local deb_code mx_order
    get_codes $tz

    vsay "deb mirror: $deb_code"
    [ ${#deb_code} -eq 0 ] && fatal "No country code found for timezone: $tz"
    [ ${#mx_order} -eq 0 ] && fatal "No MX/antiX mirrors found for timezone: $tz"

    [ "$CODES_ONLY" ] && echo -e "MX/aX code: $mx_order\n  Deb code: $deb_code"

    if [ ${#IGNORE} -gt 0 ]; then
        bl_regex=${IGNORE//,/|}
        # Remove blacklisted codes and leading commas
        mx_order=$(echo $mx_order         | sed -r -e "s/\<($bl_regex)\>//g" -e "s/^,+//" )
        US_HOST_LIST=$(echo $US_HOST_LIST | sed -r -e "s/\<($bl_regex)\>//g" -e "s/^,+//" )
    fi

    # Remove the first comma and everything after it
    local mx_code=${mx_order%%,*}

    if [ "$RANDOMIZE" ]; then
        case $mx_code in 
            la|ut) mx_code=$(random_element $US_HOST_LIST) ;;
        esac
    fi

    if [ "$HOSTS_ONLY" ]; then
        local type host
        for type in $HOST_TYPES; do
            eval host=\$${mx_code}_${type}_HOST
            echo " $type: $host"
        done
        echo "deb: ftp.$deb_code.debian.org/debian"
    fi

    [ -n "$CODES_ONLY" -o -n "$HOSTS_ONLY" ] && exit 0


    # Only update if the mirror is different from the one we want
    SED_EXPR="-e /ftp\.$deb_code\.debian\.org/!s=(http://ftp\.)[a-z][a-z](\.debian.org/debian/)=\1$deb_code\2="
    SED_EXPR_P="${SED_EXPR}p"

    assign_exprs $mx_code

    [ -d "$SDIR" ] || fatal "'$SDIR' is not a directory"

    local file fcnt=0
    for file in $(find $SDIR -maxdepth 1 -name "*.list"); do

        # Use diff to see if there would be any change to the file
        local diff=$(sed -r $SED_EXPR $file | diff -q $file -)
        [ "$diff" ] || continue

        fcnt=$((fnct + 1))
        if [ "$PRETEND" -o "$VERBOSE" ]; then
            echo "File: $(basename $file)"
            sed -n -r $SED_EXPR_P $file
        fi

        [ "$PRETEND" ] && continue

        [ -z "$VERBOSE" ] && qsay "File: $(basename $file)"
        sed -i -r $SED_EXPR $file
    done
}

# Add "-e $REGEX" and add "-e ${REGEX}p" to SED_EXPR and SED_EXPR_P.
# Totally data-driven.  Add more mirror sets and/or more mirrors by merely
# adding (and adding to) variables.  Relies on no spaces or tabs in the
# hostnames.  If this is violated then we could migrate to Bash lists.

assign_exprs() {
    local prefix=$1  type host
    for type in $HOST_TYPES; do
        eval host=\$${prefix}_${type}_HOST
        local oprefix ohost_list= ohost
        for oprefix in $HOST_PREFIXES; do
            [ "$oprefix" = "$prefix" ] && continue
            eval ohost=\$${oprefix}_${type}_HOST
            ohost_list=$ohost_list${ohost_list:+|}$ohost
        done
        ohost_list=$(echo $ohost_list | sed 's/\./\\\./g')
        local sed="s=($ohost_list)/=$host/="
        #echo SED_$type=$sed
        SED_EXPR="$SED_EXPR -e $sed"
        SED_EXPR_P="$SED_EXPR_P -e ${sed}p"
    done
}
# Output one of the input arguments at random
random_element() {
    local cnt=$#
    local rand=$(($RANDOM % cnt))
    shift $rand
    echo $1
}


find_zonetab_file() {
    local z dir=${1:-$ZDIR}

    ZONE_TAB=
    for z in zone.tab zone1970.tab; do
        test -r $dir/$z || continue
        ZONE_TAB=$dir/$z
        return 0
    done
    return 1
}

country_code_to_timezone() {
    local ccode=$1

    case $ccode in
        uk) ccode=gb ;;
    esac

    find_zonetab_file || fatal "Could not find zone.tab file"

    NEW_TZ=$(ccode_to_tz $ccode)
    [ -z "$NEW_TZ" ] && fatal "Could not find a timezone for country: $ccode"
    vsay "Found timezone: $NEW_TZ for country code: $ccode"
}

ccode_to_tz() {
    local code=$1
    cut -s -f1,3 $ZONE_TAB | grep -i "^$code\s" | head -n1 | cut -f2
}

error() {
    echo "$ME Error: $*" >&2
}

fatal() {
    echo "$ME Fatal Error: $*" >&2
    exit 5
}

not_setting() {
    local tz=$1
    printf "Not setting repository mirrors based on %s timezone\n"  "$tz"
    exit 0
}

vsay() {
    [ "$VERBOSE" ] || return
    echo "$*"
}

qsay() {
    [ "$QUIET" ] && return
    echo "$*"
}

list_mirrors() {
    local pre ax_host mp_host mx_host location
    for pre in  $MIRROR_PREFIXES; do
        eval ax_host=\$${pre}_AX_HOST
        eval mp_host=\$${pre}_MP_HOST
        eval mx_host=\$${pre}_MX_HOST
        eval location=\$${pre}_LOCATION

        cat << List_Mirrors
    Code: $pre
Location: $location
   antiX: $ax_host
   Mepis: $mp_host
      MX: $mx_host

List_Mirrors
    done
}

list_mirror_codes() {
    local pre location
    for pre in  $MIRROR_PREFIXES; do
        eval location=\$${pre}_LOCATION
        printf "%2s: %s\n" "$pre" "$location"
    done
}

get_codes() {
    local tz=$1
    case $tz in
                       Africa/Dakar) deb_code=pt ; mx_order=it,nl,gr,de,dk,pl,se,ut,co,ec,ru,la,tw,nz ;;
                      Africa/Banjul) deb_code=pt ; mx_order=it,nl,gr,de,dk,pl,se,ut,co,ec,ru,la,tw,nz ;;
                  Africa/Nouakchott) deb_code=pt ; mx_order=it,nl,gr,de,dk,pl,se,ru,ut,co,ec,la,tw,nz ;;
                      Africa/Bissau) deb_code=pt ; mx_order=it,gr,nl,de,dk,pl,se,co,ec,ut,ru,la,tw,nz ;;
                     Africa/Conakry) deb_code=br ; mx_order=it,gr,nl,de,dk,pl,se,co,ec,ru,ut,la,tw,nz ;;
                    Africa/Freetown) deb_code=br ; mx_order=it,gr,nl,de,dk,pl,se,co,ec,ru,ut,la,tw,nz ;;
                    Africa/El_Aaiun) deb_code=pt ; mx_order=it,nl,de,gr,dk,pl,se,ru,ut,co,ec,la,tw,nz ;;
                    Africa/Monrovia) deb_code=br ; mx_order=it,gr,nl,de,dk,pl,se,ru,co,ec,ut,la,tw,nz ;;
                      Africa/Bamako) deb_code=pt ; mx_order=it,gr,nl,de,dk,pl,se,ru,ut,co,ec,la,tw,nz ;;
                  Africa/Casablanca) deb_code=pt ; mx_order=it,nl,de,gr,dk,pl,se,ru,ut,co,ec,la,tw,nz ;;
                       Africa/Ceuta) deb_code=pt ; mx_order=it,nl,de,gr,dk,pl,se,ru,ut,co,ec,la,tw,nz ;;
                     Africa/Abidjan) deb_code=br ; mx_order=it,gr,nl,de,pl,dk,se,ru,co,ec,ut,la,tw,nz ;;
                 Africa/Ouagadougou) deb_code=pt ; mx_order=it,gr,nl,de,pl,dk,se,ru,ut,co,ec,la,tw,nz ;;
                       Africa/Accra) deb_code=pt ; mx_order=it,gr,nl,de,pl,dk,se,ru,co,ec,ut,la,tw,nz ;;
                        Africa/Lome) deb_code=pt ; mx_order=it,gr,nl,de,pl,dk,se,ru,ut,co,ec,la,tw,nz ;;
                      Africa/Niamey) deb_code=pt ; mx_order=it,gr,nl,de,pl,dk,se,ru,ut,co,ec,la,tw,nz ;;
                       Africa/Porto) deb_code=pt ; mx_order=it,gr,nl,de,pl,dk,se,ru,ut,co,ec,la,tw,nz ;;
                     Africa/Algiers) deb_code=es ; mx_order=it,nl,gr,de,dk,pl,se,ru,ut,co,ec,la,tw,nz ;;
                       Africa/Lagos) deb_code=pt ; mx_order=it,gr,nl,de,pl,dk,se,ru,ut,co,ec,la,tw,nz ;;
                    Africa/Sao_Tome) deb_code=pt ; mx_order=gr,it,nl,de,pl,dk,se,ru,co,ec,ut,tw,la,nz ;;
                      Africa/Malabo) deb_code=gr ; mx_order=gr,it,nl,de,pl,dk,se,ru,ut,co,ec,tw,la,nz ;;
                  Africa/Libreville) deb_code=gr ; mx_order=gr,it,nl,de,pl,dk,se,ru,co,ec,ut,tw,la,nz ;;
                      Africa/Douala) deb_code=gr ; mx_order=gr,it,nl,de,pl,dk,se,ru,ut,co,ec,tw,la,nz ;;
                       Africa/Tunis) deb_code=it ; mx_order=it,gr,de,nl,pl,dk,se,ru,ut,co,ec,tw,la,nz ;;
                     Africa/Tripoli) deb_code=it ; mx_order=it,gr,de,pl,nl,dk,se,ru,ut,co,ec,tw,la,nz ;;
                      Africa/Luanda) deb_code=br ; mx_order=gr,it,de,pl,nl,dk,ru,se,co,ec,ut,tw,la,nz ;;
                    Africa/Ndjamena) deb_code=gr ; mx_order=gr,it,de,pl,nl,dk,ru,se,ut,co,ec,tw,la,nz ;;
                 Africa/Brazzaville) deb_code=gr ; mx_order=gr,it,de,pl,nl,dk,ru,se,co,ec,ut,tw,la,nz ;;
                    Africa/Kinshasa) deb_code=gr ; mx_order=gr,it,de,pl,nl,dk,ru,se,co,ec,ut,tw,la,nz ;;
                    Africa/Windhoek) deb_code=br ; mx_order=gr,it,pl,de,nl,dk,ru,se,co,ec,ut,tw,nz,la ;;
                      Africa/Bangui) deb_code=gr ; mx_order=gr,it,pl,de,nl,dk,ru,se,ut,co,ec,tw,la,nz ;;
                    Africa/Gaborone) deb_code=br ; mx_order=gr,it,pl,de,nl,ru,dk,se,co,ec,tw,nz,ut,la ;;
                  Africa/Lubumbashi) deb_code=gr ; mx_order=gr,it,pl,de,nl,ru,dk,se,tw,co,ec,ut,nz,la ;;
                      Africa/Maseru) deb_code=br ; mx_order=gr,it,pl,de,nl,ru,dk,se,co,ec,tw,nz,ut,la ;;
                Africa/Johannesburg) deb_code=br ; mx_order=gr,it,pl,de,nl,ru,dk,se,co,ec,tw,nz,ut,la ;;
                      Africa/Lusaka) deb_code=gr ; mx_order=gr,it,pl,de,nl,ru,dk,se,tw,co,ec,ut,nz,la ;;
                   Africa/Bujumbura) deb_code=gr ; mx_order=gr,it,pl,de,ru,nl,dk,se,tw,ut,co,ec,nz,la ;;
                      Africa/Kigali) deb_code=gr ; mx_order=gr,it,pl,de,ru,nl,dk,se,tw,ut,co,ec,nz,la ;;
                      Africa/Harare) deb_code=gr ; mx_order=gr,it,pl,de,ru,nl,dk,se,tw,co,ec,ut,nz,la ;;
                     Africa/Mbabane) deb_code=gr ; mx_order=gr,it,pl,de,nl,ru,dk,se,tw,co,ec,nz,ut,la ;;
                       Africa/Cairo) deb_code=gr ; mx_order=gr,it,pl,ru,de,dk,nl,se,tw,ut,co,ec,la,nz ;;
                        Africa/Juba) deb_code=gr ; mx_order=gr,it,pl,de,ru,nl,dk,se,tw,ut,co,ec,la,nz ;;
                     Africa/Kampala) deb_code=gr ; mx_order=gr,it,pl,de,ru,nl,dk,se,tw,ut,co,ec,nz,la ;;
                    Africa/Khartoum) deb_code=gr ; mx_order=gr,it,pl,de,ru,dk,nl,se,tw,ut,co,ec,la,nz ;;
                      Africa/Maputo) deb_code=ir ; mx_order=gr,it,pl,de,ru,nl,dk,se,tw,co,ec,nz,ut,la ;;
                    Africa/Blantyre) deb_code=ir ; mx_order=gr,it,pl,de,ru,nl,dk,se,tw,co,ec,ut,nz,la ;;
                     Africa/Nairobi) deb_code=ir ; mx_order=gr,it,pl,ru,de,nl,dk,se,tw,ut,co,ec,nz,la ;;
                 Africa/Addis_Ababa) deb_code=ir ; mx_order=gr,it,pl,ru,de,dk,nl,se,tw,ut,co,ec,la,nz ;;
                      Africa/Asmara) deb_code=ir ; mx_order=gr,it,pl,ru,de,dk,nl,se,tw,ut,co,ec,la,nz ;;
               Africa/Dar_es_Salaam) deb_code=ir ; mx_order=gr,it,pl,ru,de,nl,dk,se,tw,ut,co,ec,nz,la ;;
                    Africa/Djibouti) deb_code=ir ; mx_order=gr,it,ru,pl,de,dk,nl,se,tw,ut,co,ec,nz,la ;;
                   Africa/Mogadishu) deb_code=ir ; mx_order=gr,it,ru,pl,de,dk,nl,se,tw,ut,co,ec,nz,la ;;
                       America/Adak) deb_code=us ; mx_order=la,tw,ut,se,ru,dk,pl,de,nl,it,nz,gr,co,ec ;;
                       America/Nome) deb_code=us ; mx_order=la,ut,se,ru,dk,tw,nl,de,pl,it,gr,co,ec,nz ;;
                  America/Anchorage) deb_code=us ; mx_order=la,ut,se,dk,ru,nl,de,pl,tw,it,co,ec,gr,nz ;;
                    America/Yakutat) deb_code=us ; mx_order=la,ut,se,dk,nl,ru,de,pl,tw,co,ec,it,gr,nz ;;
                     America/Dawson) deb_code=ca ; mx_order=la,ut,se,dk,nl,ru,de,pl,tw,it,co,ec,gr,nz ;;
                      America/Sitka) deb_code=us ; mx_order=la,ut,se,dk,nl,ru,de,pl,co,ec,tw,it,gr,nz ;;
                 America/Whitehorse) deb_code=ca ; mx_order=la,ut,se,dk,nl,ru,de,pl,co,ec,it,tw,gr,nz ;;
                     America/Juneau) deb_code=us ; mx_order=la,ut,se,dk,nl,ru,de,pl,co,ec,tw,it,gr,nz ;;
                     America/Inuvik) deb_code=ca ; mx_order=la,ut,se,dk,nl,ru,de,pl,it,tw,gr,co,ec,nz ;;
                 America/Metlakatla) deb_code=us ; mx_order=la,ut,se,dk,nl,co,ec,de,ru,pl,it,tw,gr,nz ;;
                  America/Vancouver) deb_code=ca ; mx_order=la,ut,co,ec,se,dk,nl,de,ru,pl,it,tw,gr,nz ;;
                America/Fort_Nelson) deb_code=ca ; mx_order=la,ut,se,dk,nl,de,ru,pl,co,ec,it,gr,tw,nz ;;
               America/Dawson_Creek) deb_code=ca ; mx_order=la,ut,se,dk,nl,de,ru,pl,co,ec,it,gr,tw,nz ;;
                America/Los_Angeles) deb_code=us ; mx_order=la,ut,co,ec,se,nl,dk,de,pl,ru,it,nz,tw,gr ;;
                    America/Tijuana) deb_code=mx ; mx_order=la,ut,co,ec,se,nl,dk,de,pl,ru,it,nz,tw,gr ;;
                    America/Creston) deb_code=ca ; mx_order=la,ut,co,ec,se,nl,dk,de,pl,ru,it,gr,tw,nz ;;
                      America/Boise) deb_code=us ; mx_order=la,ut,co,ec,se,nl,dk,de,pl,ru,it,gr,tw,nz ;;
                America/Yellowknife) deb_code=ca ; mx_order=la,ut,se,dk,nl,de,ru,pl,co,ec,it,gr,tw,nz ;;
                   America/Edmonton) deb_code=ca ; mx_order=la,ut,co,ec,se,nl,dk,de,pl,ru,it,gr,tw,nz ;;
                    America/Phoenix) deb_code=us ; mx_order=la,ut,co,ec,nl,se,dk,de,pl,ru,it,nz,gr,tw ;;
                 America/Hermosillo) deb_code=mx ; mx_order=la,ut,co,ec,nl,se,dk,de,pl,ru,it,nz,gr,tw ;;
              America/Swift_Current) deb_code=ca ; mx_order=la,ut,co,ec,se,nl,dk,de,pl,ru,it,gr,tw,nz ;;
                   America/Mazatlan) deb_code=mx ; mx_order=la,ut,co,ec,nl,dk,se,de,pl,it,ru,nz,gr,tw ;;
                  America/Chihuahua) deb_code=mx ; mx_order=la,ut,co,ec,nl,se,dk,de,pl,it,ru,gr,nz,tw ;;
             America/Bahia_Banderas) deb_code=mx ; mx_order=la,ut,co,ec,nl,dk,se,de,pl,nz,it,ru,gr,tw ;;
              America/Cambridge_Bay) deb_code=ca ; mx_order=ut,la,se,dk,nl,de,ru,pl,it,gr,co,ec,tw,nz ;;
                     America/Denver) deb_code=us ; mx_order=la,ut,co,ec,nl,se,dk,de,pl,ru,it,gr,tw,nz ;;
                     America/Regina) deb_code=ca ; mx_order=la,ut,co,ec,se,nl,dk,de,pl,ru,it,gr,tw,nz ;;
                    America/Ojinaga) deb_code=mx ; mx_order=la,ut,co,ec,nl,se,dk,de,pl,it,ru,gr,nz,tw ;;
        America/North_Dakota/Beulah) deb_code=us ; mx_order=la,ut,co,ec,nl,se,dk,de,pl,ru,it,gr,tw,nz ;;
     America/North_Dakota/New_Salem) deb_code=us ; mx_order=la,ut,co,ec,nl,se,dk,de,pl,ru,it,gr,tw,nz ;;
        America/North_Dakota/Center) deb_code=us ; mx_order=la,ut,co,ec,nl,se,dk,de,pl,ru,it,gr,tw,nz ;;
                  America/Monterrey) deb_code=mx ; mx_order=la,ut,co,ec,nl,dk,se,de,pl,it,ru,gr,nz,tw ;;
                America/Mexico_City) deb_code=mx ; mx_order=la,co,ec,ut,nl,dk,se,de,pl,it,ru,nz,gr,tw ;;
                  America/Matamoros) deb_code=mx ; mx_order=la,ut,co,ec,nl,dk,se,de,pl,it,ru,gr,nz,tw ;;
                   America/Winnipeg) deb_code=ca ; mx_order=ut,la,co,ec,nl,se,dk,de,pl,ru,it,gr,tw,nz ;;
                   America/Resolute) deb_code=ca ; mx_order=ut,se,dk,la,nl,de,ru,pl,it,gr,co,ec,tw,nz ;;
                America/Rainy_River) deb_code=ca ; mx_order=ut,la,co,ec,nl,se,dk,de,pl,ru,it,gr,tw,nz ;;
               America/Rankin_Inlet) deb_code=ca ; mx_order=ut,la,se,nl,dk,de,pl,ru,co,ec,it,gr,tw,nz ;;
                   America/Atikokan) deb_code=ca ; mx_order=ut,la,co,ec,nl,se,dk,de,pl,ru,it,gr,tw,nz ;;
                  America/Guatemala) deb_code=sv ; mx_order=co,ec,ut,la,nl,dk,de,se,it,pl,ru,gr,nz,tw ;;
                     America/Merida) deb_code=mx ; mx_order=co,ec,ut,la,nl,dk,se,de,it,pl,ru,gr,nz,tw ;;
                America/Thunder_Bay) deb_code=ca ; mx_order=ut,la,co,ec,nl,se,dk,de,pl,it,ru,gr,tw,nz ;;
                America/El_Salvador) deb_code=sv ; mx_order=co,ec,ut,la,nl,dk,de,se,it,pl,ru,gr,nz,tw ;;
                    America/Nipigon) deb_code=ca ; mx_order=ut,la,co,ec,nl,se,dk,de,pl,it,ru,gr,tw,nz ;;
                     America/Belize) deb_code=mx ; mx_order=co,ec,ut,la,nl,dk,de,se,it,pl,ru,gr,nz,tw ;;
                    America/Chicago) deb_code=us ; mx_order=ut,la,co,ec,nl,dk,se,de,pl,it,ru,gr,tw,nz ;;
                  America/Menominee) deb_code=us ; mx_order=ut,la,co,ec,nl,dk,se,de,pl,it,ru,gr,tw,nz ;;
          America/Indiana/Vincennes) deb_code=us ; mx_order=ut,la,co,ec,nl,dk,se,de,pl,it,ru,gr,tw,nz ;;
         America/Indiana/Petersburg) deb_code=us ; mx_order=ut,la,co,ec,nl,dk,se,de,pl,it,ru,gr,tw,nz ;;
                America/Tegucigalpa) deb_code=sv ; mx_order=co,ec,ut,la,nl,dk,de,se,it,pl,ru,gr,nz,tw ;;
                     America/Cancun) deb_code=mx ; mx_order=co,ec,ut,la,nl,dk,se,de,it,pl,ru,gr,nz,tw ;;
          America/Indiana/Tell_City) deb_code=us ; mx_order=ut,la,co,ec,nl,dk,se,de,pl,it,ru,gr,tw,nz ;;
               America/Indiana/Knox) deb_code=us ; mx_order=ut,la,co,ec,nl,dk,se,de,pl,it,ru,gr,tw,nz ;;
            America/Indiana/Winamac) deb_code=us ; mx_order=ut,la,co,ec,nl,dk,se,de,pl,it,ru,gr,tw,nz ;;
            America/Indiana/Marengo) deb_code=us ; mx_order=ut,la,co,ec,nl,dk,se,de,pl,it,ru,gr,tw,nz ;;
                    America/Managua) deb_code=sv ; mx_order=co,ec,ut,la,nl,dk,de,se,it,pl,gr,ru,nz,tw ;;
       America/Indiana/Indianapolis) deb_code=us ; mx_order=ut,la,co,ec,nl,dk,se,de,pl,it,ru,gr,tw,nz ;;
        America/Kentucky/Louisville) deb_code=us ; mx_order=ut,la,co,ec,nl,dk,se,de,pl,it,ru,gr,tw,nz ;;
              America/Indiana/Vevay) deb_code=us ; mx_order=ut,la,co,ec,nl,dk,se,de,pl,it,ru,gr,tw,nz ;;
        America/Kentucky/Monticello) deb_code=us ; mx_order=ut,la,co,ec,nl,dk,se,de,pl,it,ru,gr,tw,nz ;;
                 America/Costa_Rica) deb_code=sv ; mx_order=co,ec,ut,la,nl,dk,de,se,it,pl,gr,ru,nz,tw ;;
                    America/Detroit) deb_code=us ; mx_order=ut,la,co,ec,nl,dk,se,de,pl,it,ru,gr,tw,nz ;;
                     America/Havana) deb_code=mx ; mx_order=ut,co,ec,la,nl,dk,de,se,it,pl,ru,gr,nz,tw ;;
                     America/Cayman) deb_code=mx ; mx_order=co,ec,ut,la,nl,dk,de,se,it,pl,ru,gr,nz,tw ;;
                  America/Guayaquil) deb_code=br ; mx_order=co,ec,ut,la,nl,it,dk,de,se,pl,gr,nz,ru,tw ;;
                     America/Panama) deb_code=sv ; mx_order=co,ec,ut,la,nl,dk,de,it,se,pl,gr,ru,nz,tw ;;
                    America/Toronto) deb_code=ca ; mx_order=ut,la,co,ec,nl,dk,se,de,pl,it,ru,gr,tw,nz ;;
                     America/Nassau) deb_code=mx ; mx_order=ut,co,ec,la,nl,dk,de,se,it,pl,ru,gr,nz,tw ;;
                       America/Lima) deb_code=br ; mx_order=co,ec,ut,la,nl,nz,it,dk,de,se,pl,gr,ru,tw ;;
                    America/Jamaica) deb_code=mx ; mx_order=co,ec,ut,la,nl,dk,de,se,it,pl,gr,ru,nz,tw ;;
                     America/Bogota) deb_code=br ; mx_order=co,ec,ut,la,nl,dk,it,de,se,pl,gr,ru,nz,tw ;;
                   America/New_York) deb_code=us ; mx_order=ut,la,co,ec,nl,dk,se,de,pl,it,ru,gr,tw,nz ;;
                       America/Port) deb_code=mx ; mx_order=co,ec,ut,la,nl,dk,de,it,se,pl,gr,ru,nz,tw ;;
                 America/Grand_Turk) deb_code=mx ; mx_order=co,ec,ut,la,nl,dk,de,it,se,pl,gr,ru,nz,tw ;;
                   America/Santiago) deb_code=cl ; mx_order=co,ec,ut,la,nz,it,nl,de,gr,dk,pl,se,ru,tw ;;
                      America/Aruba) deb_code=br ; mx_order=co,ec,ut,la,nl,dk,it,de,se,pl,gr,ru,nz,tw ;;
              America/Santo_Domingo) deb_code=mx ; mx_order=co,ec,ut,la,nl,dk,de,it,se,pl,gr,ru,nz,tw ;;
                   America/Eirunepe) deb_code=br ; mx_order=co,ec,ut,la,nl,it,de,dk,se,pl,gr,ru,nz,tw ;;
     America/Argentina/Rio_Gallegos) deb_code=cl ; mx_order=co,ec,nz,ut,la,it,gr,nl,de,dk,pl,se,ru,tw ;;
                    America/Curacao) deb_code=br ; mx_order=co,ec,ut,la,nl,dk,it,de,se,pl,gr,ru,nz,tw ;;
          America/Argentina/Mendoza) deb_code=cl ; mx_order=co,ec,ut,la,nz,it,nl,gr,de,dk,pl,se,ru,tw ;;
                      America/Thule) deb_code=ca ; mx_order=se,dk,nl,ut,de,pl,ru,it,la,gr,co,ec,tw,nz ;;
         America/Argentina/San_Juan) deb_code=cl ; mx_order=co,ec,ut,la,nz,it,nl,de,gr,dk,pl,se,ru,tw ;;
                    America/Iqaluit) deb_code=ca ; mx_order=ut,nl,se,dk,de,la,pl,ru,it,gr,co,ec,tw,nz ;;
          America/Argentina/Ushuaia) deb_code=cl ; mx_order=co,ec,nz,ut,la,it,gr,nl,de,dk,pl,se,ru,tw ;;
                 America/Kralendijk) deb_code=br ; mx_order=co,ec,ut,la,nl,dk,it,de,se,pl,gr,ru,nz,tw ;;
                     America/La_Paz) deb_code=br ; mx_order=co,ec,ut,la,nl,it,de,dk,nz,gr,se,pl,ru,tw ;;
                 America/Rio_Branco) deb_code=br ; mx_order=co,ec,ut,la,nl,it,de,dk,se,gr,pl,nz,ru,tw ;;
                    America/Caracas) deb_code=br ; mx_order=co,ec,ut,la,nl,it,dk,de,se,pl,gr,ru,nz,tw ;;
         America/Argentina/La_Rioja) deb_code=cl ; mx_order=co,ec,ut,la,nz,it,nl,de,gr,dk,pl,se,ru,tw ;;
         America/Argentina/San_Luis) deb_code=cl ; mx_order=co,ec,ut,la,nz,it,nl,gr,de,dk,pl,se,ru,tw ;;
                America/Puerto_Rico) deb_code=br ; mx_order=co,ec,ut,la,nl,dk,de,it,se,pl,gr,ru,nz,tw ;;
        America/Argentina/Catamarca) deb_code=cl ; mx_order=co,ec,ut,la,nz,it,nl,de,gr,dk,pl,se,ru,tw ;;
                America/Pangnirtung) deb_code=ca ; mx_order=ut,se,nl,dk,de,pl,la,ru,it,gr,co,ec,tw,nz ;;
            America/Argentina/Salta) deb_code=cl ; mx_order=co,ec,ut,la,nz,it,nl,de,dk,gr,pl,se,ru,tw ;;
            America/Argentina/Jujuy) deb_code=cl ; mx_order=co,ec,ut,la,it,nz,nl,de,dk,gr,pl,se,ru,tw ;;
          America/Argentina/Tucuman) deb_code=cl ; mx_order=co,ec,ut,la,nz,it,nl,de,gr,dk,pl,se,ru,tw ;;
                  America/St_Thomas) deb_code=br ; mx_order=co,ec,ut,la,nl,dk,de,it,se,pl,gr,ru,nz,tw ;;
                    America/Moncton) deb_code=ca ; mx_order=ut,la,co,ec,nl,dk,se,de,pl,it,ru,gr,tw,nz ;;
                    America/Tortola) deb_code=br ; mx_order=co,ec,ut,la,nl,dk,de,it,se,pl,gr,ru,nz,tw ;;
          America/Argentina/Cordoba) deb_code=cl ; mx_order=co,ec,ut,la,nz,it,nl,gr,de,dk,pl,se,ru,tw ;;
                America/Porto_Velho) deb_code=br ; mx_order=co,ec,ut,la,nl,it,de,dk,gr,se,pl,ru,nz,tw ;;
                    America/Halifax) deb_code=ca ; mx_order=ut,co,ec,la,nl,dk,se,de,it,pl,ru,gr,tw,nz ;;
                    America/Marigot) deb_code=br ; mx_order=co,ec,ut,la,nl,dk,it,de,se,pl,gr,ru,nz,tw ;;
                   America/Anguilla) deb_code=br ; mx_order=co,ec,ut,la,nl,dk,it,de,se,pl,gr,ru,nz,tw ;;
              America/Lower_Princes) deb_code=br ; mx_order=co,ec,ut,la,nl,dk,it,de,se,pl,gr,ru,nz,tw ;;
              America/St_Barthelemy) deb_code=br ; mx_order=co,ec,ut,la,nl,dk,it,de,se,pl,gr,ru,nz,tw ;;
                   America/St_Kitts) deb_code=br ; mx_order=co,ec,ut,la,nl,dk,it,de,se,pl,gr,ru,nz,tw ;;
                 America/Montserrat) deb_code=br ; mx_order=co,ec,ut,la,nl,it,dk,de,se,pl,gr,ru,nz,tw ;;
                    America/Antigua) deb_code=br ; mx_order=co,ec,ut,la,nl,it,dk,de,se,pl,gr,ru,nz,tw ;;
                    America/Grenada) deb_code=br ; mx_order=co,ec,ut,la,nl,it,dk,de,se,pl,gr,ru,nz,tw ;;
                 America/Guadeloupe) deb_code=br ; mx_order=co,ec,ut,la,nl,it,dk,de,se,pl,gr,ru,nz,tw ;;
              America/Port_of_Spain) deb_code=br ; mx_order=co,ec,ut,la,nl,it,dk,de,se,pl,gr,ru,nz,tw ;;
                   America/Dominica) deb_code=br ; mx_order=co,ec,ut,la,nl,it,dk,de,se,pl,gr,ru,nz,tw ;;
                 America/St_Vincent) deb_code=br ; mx_order=co,ec,ut,la,nl,it,dk,de,se,pl,gr,ru,nz,tw ;;
                 America/Martinique) deb_code=br ; mx_order=co,ec,ut,la,nl,it,dk,de,se,pl,gr,ru,nz,tw ;;
                   America/St_Lucia) deb_code=br ; mx_order=co,ec,ut,la,nl,it,dk,de,se,pl,gr,ru,nz,tw ;;
                  America/Boa_Vista) deb_code=br ; mx_order=co,ec,ut,la,nl,it,de,dk,se,pl,gr,ru,nz,tw ;;
                  America/Goose_Bay) deb_code=ca ; mx_order=ut,nl,dk,se,de,la,pl,it,co,ec,ru,gr,tw,nz ;;
                     America/Manaus) deb_code=br ; mx_order=co,ec,ut,la,nl,it,de,dk,se,gr,pl,ru,nz,tw ;;
                  America/Glace_Bay) deb_code=ca ; mx_order=ut,nl,co,ec,dk,la,de,se,it,pl,ru,gr,tw,nz ;;
                   America/Barbados) deb_code=br ; mx_order=co,ec,ut,la,nl,it,dk,de,se,pl,gr,ru,nz,tw ;;
     America/Argentina/Buenos_Aires) deb_code=cl ; mx_order=co,ec,ut,la,nz,it,nl,gr,de,dk,pl,se,ru,tw ;;
                     America/Guyana) deb_code=br ; mx_order=co,ec,ut,la,nl,it,de,dk,se,pl,gr,ru,nz,tw ;;
                   America/Asuncion) deb_code=br ; mx_order=co,ec,ut,la,it,nl,gr,de,dk,nz,pl,se,ru,tw ;;
                      America/Blanc) deb_code=ca ; mx_order=ut,nl,dk,se,de,pl,la,it,co,ec,ru,gr,tw,nz ;;
                   America/Miquelon) deb_code=ca ; mx_order=ut,nl,dk,de,se,co,ec,la,it,pl,ru,gr,tw,nz ;;
                 America/Montevideo) deb_code=cl ; mx_order=co,ec,ut,la,nz,it,nl,gr,de,dk,pl,se,ru,tw ;;
                     America/Cuiaba) deb_code=br ; mx_order=co,ec,ut,la,it,nl,de,dk,gr,pl,se,ru,nz,tw ;;
                 America/Paramaribo) deb_code=br ; mx_order=co,ec,ut,la,nl,it,de,dk,se,pl,gr,ru,nz,tw ;;
                   America/Santarem) deb_code=br ; mx_order=co,ec,ut,la,nl,it,de,dk,gr,pl,se,ru,nz,tw ;;
               America/Campo_Grande) deb_code=br ; mx_order=co,ec,ut,la,it,nl,gr,de,dk,pl,se,nz,ru,tw ;;
                   America/St_Johns) deb_code=ca ; mx_order=ut,nl,dk,de,se,it,pl,co,ec,la,ru,gr,tw,nz ;;
                    America/Cayenne) deb_code=br ; mx_order=co,ec,ut,nl,la,it,de,dk,gr,se,pl,ru,nz,tw ;;
                    America/Godthab) deb_code=ca ; mx_order=ut,nl,se,dk,de,pl,ru,it,la,gr,co,ec,tw,nz ;;
                      America/Belem) deb_code=br ; mx_order=co,ec,ut,it,nl,de,la,dk,gr,pl,se,ru,nz,tw ;;
                  America/Araguaina) deb_code=br ; mx_order=co,ec,ut,it,nl,la,de,dk,gr,pl,se,ru,nz,tw ;;
                  America/Sao_Paulo) deb_code=br ; mx_order=co,ec,ut,it,nl,la,gr,de,dk,pl,se,ru,nz,tw ;;
                      America/Bahia) deb_code=br ; mx_order=co,ec,ut,it,nl,gr,de,dk,pl,se,la,ru,nz,tw ;;
                  America/Fortaleza) deb_code=br ; mx_order=co,ec,ut,it,nl,gr,de,dk,pl,se,la,ru,nz,tw ;;
                     America/Maceio) deb_code=br ; mx_order=co,ec,ut,it,nl,gr,de,dk,pl,se,ru,la,nz,tw ;;
                     America/Recife) deb_code=br ; mx_order=co,ec,ut,it,nl,gr,de,dk,pl,se,ru,la,nz,tw ;;
                    America/Noronha) deb_code=br ; mx_order=co,ec,ut,it,nl,gr,de,dk,pl,se,ru,la,nz,tw ;;
               America/Scoresbysund) deb_code=ca ; mx_order=se,dk,nl,de,pl,ru,it,ut,gr,la,co,ec,tw,nz ;;
               America/Danmarkshavn) deb_code=ca ; mx_order=se,dk,nl,de,pl,ru,it,gr,ut,la,tw,co,ec,nz ;;
                 Antarctica/Rothera) deb_code=au ; mx_order=nz,co,ec,ut,la,it,gr,nl,de,dk,pl,tw,se,ru ;;
                  Antarctica/Palmer) deb_code=au ; mx_order=nz,co,ec,ut,la,it,gr,nl,de,dk,pl,se,tw,ru ;;
                   Antarctica/Troll) deb_code=au ; mx_order=nz,co,ec,gr,it,tw,ut,nl,de,pl,dk,ru,la,se ;;
                   Antarctica/Syowa) deb_code=au ; mx_order=nz,co,ec,gr,tw,it,pl,de,nl,ru,dk,se,ut,la ;;
                  Antarctica/Mawson) deb_code=au ; mx_order=nz,tw,gr,co,ec,it,pl,ru,de,nl,dk,se,ut,la ;;
                   Antarctica/Davis) deb_code=au ; mx_order=nz,tw,co,ec,gr,it,ru,pl,de,nl,dk,se,la,ut ;;
                  Antarctica/Vostok) deb_code=au ; mx_order=nz,tw,co,ec,gr,it,la,pl,ru,de,ut,nl,dk,se ;;
                   Antarctica/Casey) deb_code=au ; mx_order=nz,tw,co,ec,gr,it,ru,pl,la,de,dk,nl,se,ut ;;
          Antarctica/DumontDUrville) deb_code=au ; mx_order=nz,tw,co,ec,la,gr,it,ru,pl,ut,de,dk,se,nl ;;
               Antarctica/Macquarie) deb_code=au ; mx_order=nz,tw,la,co,ec,ut,gr,ru,it,pl,se,de,dk,nl ;;
                 Antarctica/McMurdo) deb_code=au ; mx_order=nz,co,ec,tw,la,ut,gr,it,pl,ru,de,nl,dk,se ;;
                Arctic/Longyearbyen) deb_code=is ; mx_order=se,dk,ru,de,pl,nl,it,gr,ut,la,tw,co,ec,nz ;;
                       Asia/Nicosia) deb_code=ir ; mx_order=gr,it,pl,ru,de,dk,se,nl,tw,ut,co,ec,la,nz ;;
                          Asia/Gaza) deb_code=ir ; mx_order=gr,it,pl,ru,de,dk,se,nl,tw,ut,co,ec,la,nz ;;
                        Asia/Hebron) deb_code=ir ; mx_order=gr,it,pl,ru,de,dk,se,nl,tw,ut,co,ec,la,nz ;;
                     Asia/Jerusalem) deb_code=ir ; mx_order=gr,it,pl,ru,de,dk,se,nl,tw,ut,co,ec,la,nz ;;
                        Asia/Beirut) deb_code=ir ; mx_order=gr,it,pl,ru,de,dk,se,nl,tw,ut,co,ec,la,nz ;;
                         Asia/Amman) deb_code=ir ; mx_order=gr,it,pl,ru,de,dk,se,nl,tw,ut,co,ec,la,nz ;;
                      Asia/Damascus) deb_code=ir ; mx_order=gr,it,pl,ru,de,dk,se,nl,tw,ut,co,ec,la,nz ;;
                       Asia/Baghdad) deb_code=ir ; mx_order=gr,ru,pl,it,de,se,dk,nl,tw,ut,co,ec,la,nz ;;
                       Asia/Yerevan) deb_code=ir ; mx_order=ru,gr,pl,it,de,se,dk,nl,tw,ut,la,co,ec,nz ;;
                       Asia/Tbilisi) deb_code=ir ; mx_order=ru,gr,pl,de,it,se,dk,nl,tw,ut,la,co,ec,nz ;;
                          Asia/Aden) deb_code=ir ; mx_order=gr,it,ru,pl,de,dk,se,nl,tw,ut,co,ec,nz,la ;;
                        Asia/Riyadh) deb_code=ir ; mx_order=gr,ru,it,pl,de,dk,se,nl,tw,ut,co,ec,la,nz ;;
                        Asia/Kuwait) deb_code=ir ; mx_order=gr,ru,pl,it,de,se,dk,nl,tw,ut,co,ec,la,nz ;;
                          Asia/Baku) deb_code=ir ; mx_order=ru,gr,pl,se,de,it,dk,nl,tw,ut,la,co,ec,nz ;;
                         Asia/Aqtau) deb_code=ir ; mx_order=ru,pl,gr,se,de,dk,it,nl,tw,ut,la,co,ec,nz ;;
                       Asia/Bahrain) deb_code=ir ; mx_order=gr,ru,pl,it,de,se,dk,nl,tw,ut,co,ec,la,nz ;;
                          Asia/Oral) deb_code=ru ; mx_order=ru,pl,se,de,dk,gr,it,nl,tw,ut,la,co,ec,nz ;;
                        Asia/Tehran) deb_code=ir ; mx_order=ru,gr,pl,it,de,se,dk,nl,tw,ut,la,co,ec,nz ;;
                         Asia/Qatar) deb_code=ir ; mx_order=gr,ru,pl,it,de,se,dk,nl,tw,ut,co,ec,la,nz ;;
                         Asia/Dubai) deb_code=ir ; mx_order=gr,ru,pl,it,de,se,dk,nl,tw,ut,la,co,ec,nz ;;
                        Asia/Aqtobe) deb_code=ru ; mx_order=ru,pl,se,gr,dk,de,it,nl,tw,ut,la,co,ec,nz ;;
                      Asia/Ashgabat) deb_code=ir ; mx_order=ru,gr,pl,se,de,it,dk,nl,tw,ut,la,co,ec,nz ;;
                        Asia/Muscat) deb_code=ir ; mx_order=gr,ru,pl,it,de,se,dk,nl,tw,ut,la,nz,co,ec ;;
                 Asia/Yekaterinburg) deb_code=ru ; mx_order=ru,se,pl,dk,de,gr,nl,it,tw,ut,la,co,ec,nz ;;
                     Asia/Qyzylorda) deb_code=ru ; mx_order=ru,pl,se,gr,de,dk,it,nl,tw,ut,la,co,ec,nz ;;
                     Asia/Samarkand) deb_code=ir ; mx_order=ru,gr,pl,se,de,dk,it,nl,tw,ut,la,co,ec,nz ;;
                       Asia/Karachi) deb_code=ir ; mx_order=ru,gr,pl,it,se,tw,de,dk,nl,ut,nz,la,co,ec ;;
                      Asia/Dushanbe) deb_code=ir ; mx_order=ru,gr,pl,se,de,dk,it,nl,tw,ut,la,nz,co,ec ;;
                         Asia/Kabul) deb_code=ir ; mx_order=ru,gr,pl,se,de,dk,it,tw,nl,ut,la,nz,co,ec ;;
                      Asia/Tashkent) deb_code=cn ; mx_order=ru,pl,gr,se,de,dk,it,nl,tw,ut,la,co,ec,nz ;;
                          Asia/Omsk) deb_code=ru ; mx_order=ru,se,pl,dk,de,gr,nl,it,tw,ut,la,co,ec,nz ;;
                       Asia/Bishkek) deb_code=cn ; mx_order=ru,pl,se,gr,dk,de,tw,it,nl,ut,la,nz,co,ec ;;
                        Asia/Almaty) deb_code=ru ; mx_order=ru,pl,se,gr,tw,dk,de,it,nl,ut,la,nz,co,ec ;;
                       Asia/Colombo) deb_code=hk ; mx_order=tw,ru,gr,pl,it,se,de,dk,nl,nz,ut,la,co,ec ;;
                   Asia/Novosibirsk) deb_code=ru ; mx_order=ru,se,pl,dk,de,tw,gr,nl,it,ut,la,co,ec,nz ;;
                       Asia/Barnaul) deb_code=ru ; mx_order=ru,se,pl,dk,tw,de,gr,nl,it,ut,la,nz,co,ec ;;
                     Asia/Kathmandu) deb_code=cn ; mx_order=tw,ru,gr,pl,se,de,dk,it,nl,nz,ut,la,co,ec ;;
                  Asia/Novokuznetsk) deb_code=ru ; mx_order=ru,se,tw,pl,dk,de,gr,nl,it,ut,la,nz,co,ec ;;
                        Asia/Urumqi) deb_code=cn ; mx_order=tw,ru,se,pl,dk,gr,de,nl,it,ut,la,nz,co,ec ;;
                       Asia/Kolkata) deb_code=cn ; mx_order=tw,ru,gr,pl,se,de,dk,it,nl,nz,ut,la,co,ec ;;
                       Asia/Thimphu) deb_code=cn ; mx_order=tw,ru,gr,pl,se,de,dk,it,nl,nz,ut,la,co,ec ;;
                         Asia/Dhaka) deb_code=cn ; mx_order=tw,ru,gr,pl,se,de,dk,it,nl,nz,ut,la,co,ec ;;
                          Asia/Hovd) deb_code=cn ; mx_order=tw,ru,se,pl,dk,de,gr,nl,it,ut,la,nz,co,ec ;;
                   Asia/Krasnoyarsk) deb_code=ru ; mx_order=ru,tw,se,pl,dk,de,nl,gr,it,ut,la,nz,co,ec ;;
                       Asia/Rangoon) deb_code=hk ; mx_order=tw,ru,gr,pl,se,de,dk,it,nl,nz,la,ut,co,ec ;;
                       Asia/Bangkok) deb_code=hk ; mx_order=tw,ru,gr,pl,se,de,dk,it,nl,nz,la,ut,co,ec ;;
                  Asia/Kuala_Lumpur) deb_code=hk ; mx_order=tw,ru,nz,gr,pl,se,de,dk,it,nl,la,ut,co,ec ;;
                     Asia/Vientiane) deb_code=hk ; mx_order=tw,ru,gr,pl,se,dk,de,it,nl,nz,la,ut,co,ec ;;
                     Asia/Singapore) deb_code=hk ; mx_order=tw,nz,ru,gr,pl,se,de,dk,it,nl,la,ut,co,ec ;;
                       Asia/Irkutsk) deb_code=ru ; mx_order=tw,ru,se,pl,dk,de,nl,gr,it,la,ut,nz,co,ec ;;
                    Asia/Phnom_Penh) deb_code=hk ; mx_order=tw,ru,gr,pl,se,nz,de,dk,it,nl,la,ut,co,ec ;;
                   Asia/Ho_Chi_Minh) deb_code=hk ; mx_order=tw,ru,gr,pl,nz,se,de,dk,it,nl,la,ut,co,ec ;;
                       Asia/Jakarta) deb_code=hk ; mx_order=tw,nz,ru,gr,pl,se,de,it,dk,nl,la,ut,co,ec ;;
                   Asia/Ulaanbaatar) deb_code=ru ; mx_order=tw,ru,se,pl,dk,de,gr,nl,it,la,ut,nz,co,ec ;;
                     Asia/Pontianak) deb_code=hk ; mx_order=tw,nz,ru,gr,pl,se,de,dk,it,nl,la,ut,co,ec ;;
                       Asia/Kuching) deb_code=hk ; mx_order=tw,nz,ru,gr,pl,se,de,dk,it,nl,la,ut,co,ec ;;
                         Asia/Chita) deb_code=ru ; mx_order=tw,ru,se,pl,dk,de,nl,gr,it,la,ut,nz,co,ec ;;
                         Asia/Macau) deb_code=hk ; mx_order=tw,ru,se,pl,gr,dk,de,nz,it,nl,la,ut,co,ec ;;
                     Asia/Hong_Kong) deb_code=hk ; mx_order=tw,ru,se,pl,gr,dk,de,nz,it,nl,la,ut,co,ec ;;
                    Asia/Choibalsan) deb_code=ru ; mx_order=tw,ru,se,pl,dk,de,nl,gr,it,la,ut,nz,co,ec ;;
                        Asia/Brunei) deb_code=hk ; mx_order=tw,nz,ru,gr,pl,se,dk,de,it,nl,la,ut,co,ec ;;
                      Asia/Makassar) deb_code=hk ; mx_order=tw,nz,ru,gr,pl,se,dk,de,it,nl,la,ut,co,ec ;;
                        Asia/Manila) deb_code=hk ; mx_order=tw,nz,ru,se,pl,gr,dk,de,it,nl,la,ut,co,ec ;;
                      Asia/Shanghai) deb_code=cn ; mx_order=tw,ru,se,pl,dk,de,gr,nl,it,nz,la,ut,co,ec ;;
                        Asia/Taipei) deb_code=tw ; mx_order=tw,ru,se,pl,nz,dk,de,gr,nl,it,la,ut,co,ec ;;
                          Asia/Dili) deb_code=hk ; mx_order=tw,nz,ru,gr,pl,se,dk,de,it,nl,la,ut,co,ec ;;
                     Asia/Pyongyang) deb_code=kr ; mx_order=tw,ru,se,pl,dk,de,gr,nl,it,la,nz,ut,co,ec ;;
                         Asia/Seoul) deb_code=kr ; mx_order=tw,ru,se,pl,dk,de,gr,nl,it,nz,la,ut,co,ec ;;
                       Asia/Yakutsk) deb_code=ru ; mx_order=tw,ru,se,pl,dk,de,nl,gr,it,la,ut,nz,co,ec ;;
                   Asia/Vladivostok) deb_code=ru ; mx_order=tw,ru,se,pl,dk,de,nl,gr,it,la,nz,ut,co,ec ;;
                      Asia/Khandyga) deb_code=ru ; mx_order=tw,ru,se,dk,pl,de,nl,gr,it,la,ut,nz,co,ec ;;
                         Asia/Tokyo) deb_code=jp ; mx_order=tw,ru,se,pl,dk,nz,la,de,nl,gr,it,ut,co,ec ;;
                      Asia/Jayapura) deb_code=tw ; mx_order=tw,nz,ru,la,se,pl,dk,gr,de,nl,it,ut,co,ec ;;
                      Asia/Sakhalin) deb_code=ru ; mx_order=tw,ru,se,pl,dk,la,de,nl,gr,it,ut,nz,co,ec ;;
                           Asia/Ust) deb_code=ru ; mx_order=tw,ru,se,dk,pl,de,nl,la,it,gr,ut,nz,co,ec ;;
                       Asia/Magadan) deb_code=ru ; mx_order=tw,ru,se,dk,pl,la,de,nl,it,gr,ut,nz,co,ec ;;
                 Asia/Srednekolymsk) deb_code=ru ; mx_order=tw,ru,se,dk,pl,de,nl,la,ut,it,gr,co,ec,nz ;;
                     Asia/Kamchatka) deb_code=ru ; mx_order=tw,la,ru,se,dk,pl,de,nl,ut,it,gr,nz,co,ec ;;
                        Asia/Anadyr) deb_code=ru ; mx_order=la,tw,se,ru,dk,ut,pl,de,nl,it,gr,co,ec,nz ;;
                   Atlantic/Bermuda) deb_code=pt ; mx_order=ut,co,ec,la,nl,dk,de,se,it,pl,gr,ru,tw,nz ;;
                   Atlantic/Stanley) deb_code=pt ; mx_order=co,ec,nz,ut,la,it,gr,nl,de,dk,pl,se,ru,tw ;;
             Atlantic/South_Georgia) deb_code=pt ; mx_order=co,ec,nz,ut,it,gr,nl,la,de,pl,dk,se,ru,tw ;;
                    Atlantic/Azores) deb_code=pt ; mx_order=nl,it,de,dk,se,pl,ut,gr,ru,co,ec,la,tw,nz ;;
                Atlantic/Cape_Verde) deb_code=pt ; mx_order=it,nl,gr,de,dk,co,ec,ut,pl,se,ru,la,tw,nz ;;
                 Atlantic/Reykjavik) deb_code=is ; mx_order=nl,dk,se,de,pl,ru,it,gr,ut,la,co,ec,tw,nz ;;
                   Atlantic/Madeira) deb_code=pt ; mx_order=it,nl,de,dk,gr,pl,se,ru,ut,co,ec,la,tw,nz ;;
                    Atlantic/Canary) deb_code=pt ; mx_order=it,nl,de,gr,dk,pl,se,ru,ut,co,ec,la,tw,nz ;;
                     Atlantic/Faroe) deb_code=is ; mx_order=nl,dk,se,de,pl,ru,it,gr,ut,la,co,ec,tw,nz ;;
                 Atlantic/St_Helena) deb_code=pt ; mx_order=it,gr,nl,de,co,ec,pl,dk,se,ru,ut,la,nz,tw ;;
                    Australia/Perth) deb_code=au ; mx_order=nz,tw,ru,gr,pl,it,se,de,dk,nl,la,co,ec,ut ;;
                    Australia/Eucla) deb_code=au ; mx_order=nz,tw,ru,gr,pl,la,se,it,de,dk,nl,co,ec,ut ;;
                   Australia/Darwin) deb_code=au ; mx_order=tw,nz,ru,gr,pl,se,la,dk,de,it,nl,ut,co,ec ;;
                 Australia/Adelaide) deb_code=au ; mx_order=nz,tw,la,ru,gr,pl,se,co,ec,de,it,dk,nl,ut ;;
              Australia/Broken_Hill) deb_code=au ; mx_order=nz,tw,la,ru,gr,pl,se,co,ec,dk,de,it,nl,ut ;;
                   Australia/Currie) deb_code=au ; mx_order=nz,tw,la,ru,co,ec,gr,pl,se,it,de,dk,nl,ut ;;
                Australia/Melbourne) deb_code=au ; mx_order=nz,tw,la,ru,co,ec,gr,pl,se,de,it,dk,nl,ut ;;
                   Australia/Hobart) deb_code=au ; mx_order=nz,tw,la,co,ec,ru,gr,pl,se,it,de,dk,ut,nl ;;
                 Australia/Lindeman) deb_code=au ; mx_order=nz,tw,la,ru,se,pl,gr,dk,de,co,ec,it,nl,ut ;;
                   Australia/Sydney) deb_code=au ; mx_order=nz,tw,la,co,ec,ru,gr,pl,se,ut,dk,de,it,nl ;;
                 Australia/Brisbane) deb_code=au ; mx_order=nz,tw,la,ru,co,ec,se,pl,gr,ut,dk,de,it,nl ;;
                Australia/Lord_Howe) deb_code=au ; mx_order=nz,tw,la,co,ec,ru,ut,se,pl,gr,dk,de,it,nl ;;
                      Europe/Lisbon) deb_code=pt ; mx_order=it,nl,de,dk,pl,gr,se,ru,ut,co,ec,la,tw,nz ;;
                      Europe/Dublin) deb_code=ie ; mx_order=nl,dk,de,se,pl,it,ru,gr,ut,co,ec,la,tw,nz ;;
                   Europe/Gibraltar) deb_code=pt ; mx_order=it,nl,de,dk,gr,pl,se,ru,ut,co,ec,la,tw,nz ;;
                 Europe/Isle_of_Man) deb_code=ie ; mx_order=nl,dk,de,se,pl,it,ru,gr,ut,co,ec,la,tw,nz ;;
                      Europe/Madrid) deb_code=es ; mx_order=it,nl,de,dk,pl,gr,se,ru,ut,co,ec,la,tw,nz ;;
                    Europe/Guernsey) deb_code=uk ; mx_order=nl,de,dk,it,pl,se,gr,ru,ut,co,ec,la,tw,nz ;;
                      Europe/Jersey) deb_code=uk ; mx_order=nl,de,dk,it,pl,se,gr,ru,ut,co,ec,la,tw,nz ;;
                      Europe/London) deb_code=uk ; mx_order=nl,de,dk,se,it,pl,gr,ru,ut,co,ec,la,tw,nz ;;
                     Europe/Andorra) deb_code=es ; mx_order=it,nl,de,dk,pl,gr,se,ru,ut,co,ec,la,tw,nz ;;
                       Europe/Paris) deb_code=fr ; mx_order=nl,de,dk,it,pl,se,gr,ru,ut,co,ec,la,tw,nz ;;
                    Europe/Brussels) deb_code=be ; mx_order=nl,de,dk,it,pl,se,gr,ru,ut,co,ec,la,tw,nz ;;
                   Europe/Amsterdam) deb_code=nl ; mx_order=nl,de,dk,pl,se,it,ru,gr,ut,co,ec,la,tw,nz ;;
                  Europe/Luxembourg) deb_code=be ; mx_order=nl,de,dk,it,pl,se,gr,ru,ut,co,ec,la,tw,nz ;;
                      Europe/Monaco) deb_code=ch ; mx_order=it,nl,de,dk,pl,gr,se,ru,ut,co,ec,la,tw,nz ;;
                      Europe/Zurich) deb_code=ch ; mx_order=nl,de,it,dk,pl,se,gr,ru,ut,co,ec,la,tw,nz ;;
                    Europe/Busingen) deb_code=de ; mx_order=nl,de,it,dk,pl,se,gr,ru,ut,co,ec,la,tw,nz ;;
                       Europe/Vaduz) deb_code=ch ; mx_order=de,it,nl,dk,pl,se,gr,ru,ut,co,ec,tw,la,nz ;;
                        Europe/Oslo) deb_code=no ; mx_order=se,dk,de,nl,pl,ru,it,gr,ut,la,tw,co,ec,nz ;;
                     Europe/Vatican) deb_code=it ; mx_order=it,gr,de,nl,pl,dk,se,ru,ut,co,ec,tw,la,nz ;;
                  Europe/San_Marino) deb_code=it ; mx_order=it,de,nl,gr,pl,dk,se,ru,ut,co,ec,tw,la,nz ;;
                        Europe/Rome) deb_code=it ; mx_order=it,gr,de,nl,pl,dk,se,ru,ut,co,ec,tw,la,nz ;;
                  Europe/Copenhagen) deb_code=dk ; mx_order=dk,de,se,nl,pl,it,ru,gr,ut,tw,la,co,ec,nz ;;
                      Europe/Berlin) deb_code=de ; mx_order=de,dk,pl,nl,se,it,ru,gr,ut,tw,la,co,ec,nz ;;
                      Europe/Prague) deb_code=cz ; mx_order=de,pl,dk,nl,it,se,gr,ru,ut,tw,co,ec,la,nz ;;
                       Europe/Malta) deb_code=it ; mx_order=it,gr,de,pl,nl,dk,se,ru,ut,co,ec,tw,la,nz ;;
                   Europe/Ljubljana) deb_code=si ; mx_order=it,de,pl,nl,dk,gr,se,ru,ut,tw,co,ec,la,nz ;;
                      Europe/Zagreb) deb_code=hr ; mx_order=it,de,pl,gr,nl,dk,se,ru,ut,tw,co,ec,la,nz ;;
                      Europe/Vienna) deb_code=at ; mx_order=de,pl,it,dk,nl,se,gr,ru,ut,tw,co,ec,la,nz ;;
                  Europe/Bratislava) deb_code=sk ; mx_order=pl,de,it,dk,nl,se,gr,ru,ut,tw,co,ec,la,nz ;;
                   Europe/Stockholm) deb_code=se ; mx_order=se,dk,pl,de,nl,ru,it,gr,ut,tw,la,co,ec,nz ;;
                    Europe/Sarajevo) deb_code=hr ; mx_order=it,gr,pl,de,dk,nl,se,ru,ut,tw,co,ec,la,nz ;;
                    Europe/Budapest) deb_code=hu ; mx_order=pl,de,it,dk,gr,nl,se,ru,ut,tw,co,ec,la,nz ;;
                   Europe/Podgorica) deb_code=bg ; mx_order=it,gr,pl,de,dk,nl,se,ru,ut,tw,co,ec,la,nz ;;
                      Europe/Tirane) deb_code=bg ; mx_order=gr,it,pl,de,dk,nl,se,ru,ut,tw,co,ec,la,nz ;;
                   Europe/Mariehamn) deb_code=se ; mx_order=se,dk,pl,de,ru,nl,it,gr,ut,tw,la,co,ec,nz ;;
                    Europe/Belgrade) deb_code=hu ; mx_order=it,gr,pl,de,dk,nl,se,ru,ut,tw,co,ec,la,nz ;;
                 Europe/Kaliningrad) deb_code=ru ; mx_order=pl,dk,de,se,nl,ru,it,gr,ut,tw,la,co,ec,nz ;;
                      Europe/Warsaw) deb_code=pl ; mx_order=pl,de,dk,se,nl,ru,it,gr,ut,tw,la,co,ec,nz ;;
                      Europe/Skopje) deb_code=bg ; mx_order=gr,it,pl,de,dk,nl,ru,se,ut,tw,co,ec,la,nz ;;
                    Europe/Uzhgorod) deb_code=ua ; mx_order=pl,de,dk,it,gr,se,ru,nl,ut,tw,la,co,ec,nz ;;
                       Europe/Sofia) deb_code=bg ; mx_order=gr,it,pl,de,dk,nl,ru,se,ut,tw,co,ec,la,nz ;;
                      Europe/Athens) deb_code=gr ; mx_order=gr,it,pl,de,dk,nl,ru,se,ut,tw,co,ec,la,nz ;;
                        Europe/Riga) deb_code=lt ; mx_order=se,pl,dk,ru,de,nl,it,gr,ut,tw,la,co,ec,nz ;;
                     Europe/Tallinn) deb_code=ee ; mx_order=se,pl,dk,ru,de,nl,it,gr,ut,tw,la,co,ec,nz ;;
                    Europe/Helsinki) deb_code=fi ; mx_order=se,dk,pl,ru,de,nl,it,gr,ut,tw,la,co,ec,nz ;;
                     Europe/Vilnius) deb_code=lt ; mx_order=pl,se,ru,dk,de,nl,it,gr,ut,tw,la,co,ec,nz ;;
                   Europe/Bucharest) deb_code=ro ; mx_order=gr,pl,it,de,ru,dk,se,nl,ut,tw,co,ec,la,nz ;;
                       Europe/Minsk) deb_code=by ; mx_order=pl,ru,se,de,dk,nl,it,gr,ut,tw,la,co,ec,nz ;;
                    Europe/Chisinau) deb_code=ro ; mx_order=pl,ru,gr,de,it,dk,se,nl,ut,tw,la,co,ec,nz ;;
                    Europe/Istanbul) deb_code=tr ; mx_order=gr,it,pl,de,ru,dk,se,nl,ut,tw,co,ec,la,nz ;;
                        Europe/Kiev) deb_code=ua ; mx_order=pl,ru,de,se,dk,gr,it,nl,ut,tw,la,co,ec,nz ;;
                  Europe/Simferopol) deb_code=ru ; mx_order=gr,ru,pl,de,it,dk,se,nl,tw,ut,la,co,ec,nz ;;
                  Europe/Zaporozhye) deb_code=ua ; mx_order=ru,pl,gr,de,se,dk,it,nl,tw,ut,la,co,ec,nz ;;
                      Europe/Moscow) deb_code=ru ; mx_order=ru,pl,se,dk,de,nl,gr,it,tw,ut,la,co,ec,nz ;;
                   Europe/Volgograd) deb_code=ru ; mx_order=ru,pl,gr,se,de,dk,it,nl,tw,ut,la,co,ec,nz ;;
                   Europe/Astrakhan) deb_code=ru ; mx_order=ru,pl,gr,se,de,dk,it,nl,tw,ut,la,co,ec,nz ;;
                   Europe/Ulyanovsk) deb_code=ru ; mx_order=ru,pl,se,dk,de,gr,nl,it,tw,ut,la,co,ec,nz ;;
                      Europe/Samara) deb_code=ru ; mx_order=ru,pl,se,dk,de,gr,nl,it,tw,ut,la,co,ec,nz ;;
                      Indian/Comoro) deb_code=ir ; mx_order=gr,it,pl,ru,de,dk,nl,se,tw,nz,co,ec,ut,la ;;
                     Indian/Mayotte) deb_code=ir ; mx_order=gr,it,pl,ru,de,dk,nl,se,tw,nz,co,ec,ut,la ;;
                Indian/Antananarivo) deb_code=ir ; mx_order=gr,it,pl,ru,de,dk,nl,se,tw,nz,co,ec,ut,la ;;
                     Indian/Reunion) deb_code=au ; mx_order=gr,it,ru,pl,tw,de,dk,nl,se,nz,co,ec,ut,la ;;
                        Indian/Mahe) deb_code=ir ; mx_order=gr,it,ru,pl,de,dk,se,tw,nl,nz,ut,co,ec,la ;;
                   Indian/Mauritius) deb_code=au ; mx_order=gr,it,tw,ru,pl,de,dk,se,nl,nz,co,ec,ut,la ;;
                   Indian/Kerguelen) deb_code=au ; mx_order=nz,tw,gr,it,ru,pl,de,dk,nl,se,co,ec,ut,la ;;
                      Indian/Chagos) deb_code=ir ; mx_order=tw,gr,ru,it,pl,de,se,dk,nl,nz,ut,co,ec,la ;;
                    Indian/Maldives) deb_code=ir ; mx_order=tw,gr,ru,pl,it,de,se,dk,nl,nz,ut,la,co,ec ;;
                       Indian/Cocos) deb_code=au ; mx_order=tw,nz,ru,gr,pl,it,se,de,dk,nl,la,ut,co,ec ;;
                   Indian/Christmas) deb_code=au ; mx_order=tw,nz,ru,gr,pl,se,it,de,dk,nl,la,ut,co,ec ;;
                     Pacific/Midway) deb_code=us ; mx_order=la,tw,nz,ut,ru,se,dk,pl,de,co,ec,nl,it,gr ;;
                    Pacific/Chatham) deb_code=nz ; mx_order=nz,tw,la,co,ec,ut,ru,se,gr,pl,dk,de,nl,it ;;
                     Pacific/Wallis) deb_code=nc ; mx_order=nz,tw,la,co,ec,ut,ru,se,dk,pl,de,nl,gr,it ;;
                  Pacific/Tongatapu) deb_code=nc ; mx_order=nz,tw,la,co,ec,ut,ru,se,dk,pl,de,nl,gr,it ;;
                       Pacific/Apia) deb_code=nc ; mx_order=nz,la,tw,co,ec,ut,ru,se,dk,pl,de,nl,it,gr ;;
                    Pacific/Fakaofo) deb_code=nc ; mx_order=nz,la,tw,co,ec,ut,ru,se,dk,pl,de,nl,it,gr ;;
                  Pacific/Enderbury) deb_code=us ; mx_order=nz,la,tw,co,ec,ut,ru,se,dk,pl,de,nl,it,gr ;;
                  Pacific/Pago_Pago) deb_code=nc ; mx_order=nz,la,tw,co,ec,ut,ru,se,dk,pl,nl,de,it,gr ;;
                       Pacific/Niue) deb_code=nz ; mx_order=nz,la,tw,co,ec,ut,ru,se,dk,pl,nl,de,it,gr ;;
                   Pacific/Johnston) deb_code=us ; mx_order=la,nz,tw,ut,co,ec,se,ru,dk,pl,nl,de,it,gr ;;
                  Pacific/Rarotonga) deb_code=nz ; mx_order=nz,la,co,ec,tw,ut,se,ru,dk,nl,de,pl,it,gr ;;
                   Pacific/Honolulu) deb_code=us ; mx_order=la,nz,ut,tw,co,ec,se,ru,dk,nl,de,pl,it,gr ;;
                 Pacific/Kiritimati) deb_code=us ; mx_order=nz,la,tw,co,ec,ut,se,ru,dk,nl,de,pl,it,gr ;;
                     Pacific/Tahiti) deb_code=nz ; mx_order=nz,la,co,ec,ut,tw,se,dk,nl,ru,de,pl,it,gr ;;
                  Pacific/Marquesas) deb_code=cl ; mx_order=la,nz,co,ec,ut,tw,se,nl,dk,de,ru,pl,it,gr ;;
                    Pacific/Gambier) deb_code=cl ; mx_order=nz,la,co,ec,ut,tw,nl,se,dk,de,pl,it,ru,gr ;;
                   Pacific/Pitcairn) deb_code=cl ; mx_order=nz,la,co,ec,ut,tw,nl,dk,se,de,it,pl,ru,gr ;;
                     Pacific/Easter) deb_code=cl ; mx_order=co,ec,la,nz,ut,nl,dk,it,de,se,tw,pl,gr,ru ;;
                  Pacific/Galapagos) deb_code=cl ; mx_order=co,ec,ut,la,nl,nz,dk,de,it,se,pl,gr,ru,tw ;;
                      Pacific/Palau) deb_code=nc ; mx_order=tw,nz,ru,se,pl,la,dk,gr,de,nl,it,ut,co,ec ;;
                       Pacific/Guam) deb_code=nc ; mx_order=tw,nz,ru,la,se,pl,dk,de,gr,nl,it,ut,co,ec ;;
                     Pacific/Saipan) deb_code=nc ; mx_order=tw,nz,la,ru,se,pl,dk,de,gr,nl,it,ut,co,ec ;;
               Pacific/Port_Moresby) deb_code=nc ; mx_order=nz,tw,la,ru,se,pl,dk,gr,de,nl,it,ut,co,ec ;;
                      Pacific/Chuuk) deb_code=nc ; mx_order=tw,nz,la,ru,se,pl,dk,de,gr,nl,ut,it,co,ec ;;
               Pacific/Bougainville) deb_code=nc ; mx_order=nz,tw,la,ru,se,pl,dk,ut,de,gr,nl,co,ec,it ;;
                    Pacific/Pohnpei) deb_code=nc ; mx_order=tw,nz,la,ru,se,pl,dk,ut,de,nl,gr,it,co,ec ;;
                Pacific/Guadalcanal) deb_code=nc ; mx_order=nz,tw,la,ru,se,ut,pl,co,ec,dk,de,gr,nl,it ;;
                     Pacific/Kosrae) deb_code=nc ; mx_order=nz,tw,la,ru,se,ut,pl,dk,de,nl,co,ec,gr,it ;;
                     Pacific/Noumea) deb_code=nc ; mx_order=nz,tw,la,co,ec,ut,ru,se,pl,dk,de,gr,nl,it ;;
                       Pacific/Wake) deb_code=us ; mx_order=tw,nz,la,ru,se,ut,dk,pl,de,nl,gr,it,co,ec ;;
                      Pacific/Nauru) deb_code=nc ; mx_order=nz,tw,la,ru,ut,se,co,ec,pl,dk,de,nl,gr,it ;;
                  Pacific/Kwajalein) deb_code=nc ; mx_order=nz,tw,la,ru,ut,se,dk,pl,de,nl,co,ec,gr,it ;;
                    Pacific/Norfolk) deb_code=nc ; mx_order=nz,tw,la,co,ec,ut,ru,se,pl,dk,gr,de,nl,it ;;
                      Pacific/Efate) deb_code=nc ; mx_order=nz,tw,la,co,ec,ut,ru,se,pl,dk,de,nl,gr,it ;;
                     Pacific/Majuro) deb_code=nc ; mx_order=nz,tw,la,ut,ru,se,co,ec,dk,pl,de,nl,gr,it ;;
                     Pacific/Tarawa) deb_code=nc ; mx_order=nz,tw,la,ut,co,ec,ru,se,dk,pl,de,nl,gr,it ;;
                   Pacific/Auckland) deb_code=nz ; mx_order=nz,tw,la,co,ec,ut,ru,se,pl,gr,dk,de,nl,it ;;
                       Pacific/Fiji) deb_code=nc ; mx_order=nz,tw,la,co,ec,ut,ru,se,dk,pl,de,nl,gr,it ;;
                   Pacific/Funafuti) deb_code=nc ; mx_order=nz,tw,la,co,ec,ut,ru,se,dk,pl,de,nl,gr,it ;;
    esac
}

main "$@"
