#!/bin/sh -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ] ; then

FILE="/etc/apt/sources.list.d/mx.list"


# if the entry is present, don't do anything
# add disabled in any case

    if [ -z "$(grep "mx" "$FILE" |grep buster |grep main |grep ahs)" ]; then
        echo "" >> "$FILE"
        echo #ahs hardware stack repo >> "$FILE"
        echo "#deb $(cat /etc/apt/sources.list.d/mx.list |grep "main non-free" |cut -d" " -f2) buster ahs" >> "$FILE"
    fi 

fi

exit 0
