#!/bin/sh -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ] ; then
  
    #revised iso.mxrepo.com to la.mxrepo.com, if present in mx.list and antix.list
    if [ -e /etc/apt/sources.list.d/mx.list ]; then
        sed -i s/iso.mxrepo.com/la.mxrepo.com/ /etc/apt/sources.list.d/mx.list
    fi
    
    if [ -e /etc/apt/sources.list.d/antix.list ]; then
        sed -i s/iso.mxrepo.com/la.mxrepo.com/ /etc/apt/sources.list.d/antix.list
    fi
    
    
    
fi

#DEBHELPER#
